using System.ComponentModel.DataAnnotations;
using Ivy.Views.Forms;

namespace Ivy.Test;

public class TestModel
{
    [Required]
    public string RequiredString { get; set; } = string.Empty;

    public string? NullableString { get; set; }

    public string NonNullableString { get; set; } = string.Empty;

    public decimal Decimal { get; set; } = 1;
}

public class DisplayAttributeTestModel
{
    [Display(Name = "Where are you based?")]
    public int CountryId { get; set; }

    [Display(Name = "User ID")]
    public int UserId { get; set; }

    [Display(Name = "Government ID")]
    public int GovId { get; set; }

    [Display(Name = "Id")]
    public int Id { get; set; }

    public int AutoGeneratedCountryId { get; set; }

    public int AutoGeneratedUserId { get; set; }

    public int GovIdAuto { get; set; }

    public int PlainId { get; set; }
}

public class FormHelpersTest
{
    [Fact]
    public void IsRequired_ShouldReturnTrue_WhenRequiredAttributeIsPresentOnProperty()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.RequiredString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnFalse_WhenPropertyIsNullableString()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.NullableString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnTrue_WhenPropertyIsNonNullableStringWithoutRequiredAttribute()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.NonNullableString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnFalse_WhenPropertyIsNotString()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.Decimal));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.False(result);
    }
}

public class FormScaffolderTest
{
    [Fact]
    public void ScaffoldFields_ShouldNotTruncateDisplayAttributeName_WhenFieldNameEndsWithId()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        Assert.Equal("Where are you based?", fields["CountryId"].Label);
        Assert.Equal("User ID", fields["UserId"].Label);
        Assert.Equal("Government ID", fields["GovId"].Label);
        Assert.Equal("Id", fields["Id"].Label);
    }

    [Fact]
    public void ScaffoldFields_ShouldTrimIdSuffix_FromAutoGeneratedLabels()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        Assert.Equal("Auto Generated Country", fields["AutoGeneratedCountryId"].Label);
        Assert.Equal("Auto Generated User", fields["AutoGeneratedUserId"].Label);
    }

    [Fact]
    public void ScaffoldFields_ShouldNotTrimIdSuffix_FromGovIdOrPlainId()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        // GovIdAuto should not be trimmed because it doesn't end with "Id" (it ends with "Auto")
        Assert.Equal("Gov Id Auto", fields["GovIdAuto"].Label);
        // PlainId should be trimmed to "Plain" (not "Id" or "GovId")
        Assert.Equal("Plain", fields["PlainId"].Label);
    }
}